<script setup>
const legalContent = "<p><h1>Privacy Policy</h1></p><p><strong>Last updated:</strong> January 1, 2026</p><p><h2>Overview</h2></p><p>Phifer Web Solutions (\"we,\" \"us,\" or \"our\") operates phiferwebsolutions.com and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard your information when you visit our website.</p><p><h2>Information We Collect</h2></p><p><strong>Information you provide directly:</strong>\n- Contact form submissions (name, email, phone, message)\n- Email newsletter sign-ups</p><p>\n<strong>Information collected automatically:</strong>\n- Browser type and operating system\n- Pages visited and time spent on site\n- IP address (anonymized where possible)\n- Referring website</p><p>We use cookies and similar tracking technologies. See our Cookie Policy for details.</p><p><h2>How We Use Your Information</h2></p><p>We use collected information to:\n- Respond to your inquiries and service requests\n- Send relevant communications you have opted into\n- Improve our website and services\n- Comply with legal obligations</p><p>\nWe do not sell, trade, or rent your personal information to third parties.</p><p><h2>Data Retention</h2></p><p>We retain your personal information only as long as necessary to fulfill the purposes outlined in this policy or as required by law.</p><p><h2>Your Rights</h2></p><p>You have the right to:\n- Request access to your personal data\n- Request correction of inaccurate data\n- Request deletion of your data\n- Opt out of marketing communications at any time</p><p>To exercise these rights, contact us at eric@ericphiferllc.com.</p><p><h2>Third-Party Services</h2></p><p>Our website may use third-party services including Google Analytics, social media platforms, and embedded content. These services have their own privacy policies.</p><p><h2>Children's Privacy</h2></p><p>Our website is not directed at children under 13. We do not knowingly collect personal information from children under 13.</p><p><h2>Changes to This Policy</h2></p><p>We may update this Privacy Policy periodically. We will notify you of significant changes by posting a notice on our website.</p><p><h2>Contact Us</h2></p><p>If you have questions about this Privacy Policy, contact us at:</p><p><strong>Phifer Web Solutions</strong>\nEmail: eric@ericphiferllc.com\nWebsite: phiferwebsolutions.com</p>";
</script>

<template>
  <main class="page page--privacy-policy">
    <h1>Privacy Policy</h1>
    <div class="legal-content" v-html="legalContent"></div>
  </main>
</template>
