<script setup>
const legalContent = "<p><h1>Terms & Conditions</h1></p><p><strong>Last updated:</strong> January 1, 2026</p><p><h2>Agreement to Terms</h2></p><p>By accessing and using the website at phiferwebsolutions.com, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use this site.</p><p><h2>Use of This Website</h2></p><p>You may use this website for lawful purposes only. You agree not to:\n- Use this site in any way that violates applicable local, state, or federal laws\n- Attempt to gain unauthorized access to any part of the site\n- Transmit harmful, offensive, or disruptive content\n- Use automated tools to scrape or harvest data from this site</p><p><h2>Intellectual Property</h2></p><p>All content on this website — including text, images, logos, and design — is the property of Phifer Web Solutions and is protected by applicable intellectual property laws. You may not reproduce, distribute, or use our content without prior written permission.</p><p><h2>Disclaimer of Warranties</h2></p><p>This website is provided \"as is\" without warranties of any kind, either express or implied. Phifer Web Solutions does not warrant that the site will be error-free, uninterrupted, or free of viruses or other harmful components.</p><p><h2>Limitation of Liability</h2></p><p>To the fullest extent permitted by law, Phifer Web Solutions shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of this website.</p><p><h2>Links to Third-Party Websites</h2></p><p>This site may contain links to external websites. Phifer Web Solutions is not responsible for the content or privacy practices of those sites.</p><p><h2>Changes to These Terms</h2></p><p>We reserve the right to update these Terms & Conditions at any time. Continued use of the site after changes are posted constitutes your acceptance of the revised terms.</p><p><h2>Governing Law</h2></p><p>These Terms are governed by the laws of the state in which Phifer Web Solutions operates, without regard to conflict of law provisions.</p><p><h2>Contact Us</h2></p><p>For questions about these Terms, contact us at:</p><p><strong>Phifer Web Solutions</strong>\nEmail: eric@ericphiferllc.com\nWebsite: phiferwebsolutions.com</p>";
</script>

<template>
  <main class="page page--terms-and-conditions">
    <h1>Terms & Conditions</h1>
    <div class="legal-content" v-html="legalContent"></div>
  </main>
</template>
